my-wpdb:
  image: mysql:5.7
  ports:
    - "8081:3306"
  environment:
    MYSQL_ROOT_PASSWORD: wordpress
  
my-wp:
  build: ./wp
  volumes:
    - ./wp/install:/var/www/html
  ports:
    - "8080:80"
  links:
    - my-wpdb:mysql
  environment:
    WORDPRESS_DB_PASSWORD: wordpress

setup:
  build: ./scripts
  volumes_from:
    - my-wp
  links:
    - my-wpdb:mysql
  entrypoint: bash  
  command: ""

frontend:
  build: ./frontend
  ports:
    - "3333:3333"
  entrypoint: yarn
  command: "run start"

community-db:
  image: postgres
  ports:
    - "5432:5432"

community:
  build: ./community
  ports:
    - "3214:3000"
  links:
    - community-db
  entrypoint: nodemon
  command: "app.js"